services:
  fetchapi:
    build: ./FetchAPI
    image: fetchapi
    container_name: fetchapi
    environment:
      POSTGRES_PASSWORD: docker
    networks:
     - ams_network
  
  db:
    build: ./db
    container_name: db
    volumes:
      - ./db/data:/var/lib/postgresql
    networks:
      - ams_network
    ports:
      - "5432:5432"

  ServeurWeb:
    build: 
      context: ./ServeurWeb
      dockerfile: Dockerfile
    image: serveurweb
    container_name: serveurweb
    ports:
      - "8080:80"
    networks:
      - ams_network
  
networks:
  ams_network:
    driver: bridge
