apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: ams-application-gla-db:latest
          env:
            - name: POSTGRES_USER
              value: "docker"
            - name: POSTGRES_PASSWORD
              value: "docker"
            - name: POSTGRES_DB
              value: "info_crypto"
          ports:
            - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetchapi-Deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: fetchapi
  template:
    metadata:
      labels:
        app: fetchapi
    spec:
      containers:
        - name: fetchapi
          image: ams-application-gla-fetchapi:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serveurweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serveurweb
  template:
    metadata:
      labels:
        app: serveurweb
    spec:
      containers: 
        - name: serveurweb
          image: ams-application-gla-serveurweb:latest
          ports:
            - containerPort: 80