apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: ams-application-gla-db:latest
          ports:
            - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetchapi-worker-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: fetchapi-worker
  template:
    metadata:
      labels:
        app: fetchapi-worker
    spec:
      containers:
        - name: fetchapi-worker
          image: ams-application-gla-fetchapi-worker:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetchapi-beat-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: fetchapi-beat
  template:
    metadata:
      labels:
        app: fetchapi-beat
    spec:
      containers:
        - name: fetchapi-beat
          image: ams-application-gla-fetchapi-beat:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serveurweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serveurweb
  template:
    metadata:
      labels:
        app: serveurweb
    spec:
      containers: 
        - name: serveurweb
          image: ams-application-gla-serveurweb:latest
          ports:
            - containerPort: 80