sonar.projectKey=anthonycam-angosto_serveurweb
sonar.projectName=ServeurWeb
sonar.organization=anthonycam-angosto
sonar.sources=src/main/java/com/analyse_crypto/app
sonar.tests=src/test/java/com/analyse_crypto/app
sonar.java.binaries=target/classes
sonar.language=java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
