management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.endpoint.prometheus.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/info_crypto
spring.datasource.username=docker
spring.datasource.password=docker
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration SMTP pour dev : MailHog local (facilite les tests)
# MailHog expose SMTP sur le port 1025 et l'UI sur 8025
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8

# Expéditeur par défaut (optionnel)
app.mail.from=no-reply@cryptoview.local