sonar.projectKey=anthonycam-angosto_fetchapi
sonar.projectName=FetchAPI
sonar.organization=anthonycam-angosto
sonar.sources=app/src
sonar.language=py
sonar.python.coverage.reportPaths=app/coverage.xml